Add missing instances to (:&)
bitemyapp/esqueleto pull request #291
Opened 2021-09-28 18:59 UTC by m4dc4p

The (:&) operator has an instance for `SqlSelect`, but none
for `ToAlias` and `ToAliasReference`. Adding those for parity.

I'm not sure if the should be a patch or major version bump. Adding new instances can break existing code, but they are such small instances ... I guessed and bumped the patch number.

I was unable to get the testing environment working locally, so I was going to rely on CI to execute my tests.  🤞 

Related to #290.

- [ ] Bumped the version number.
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock.
- [ ] Ran `stylish-haskell` and otherwise adhered to the [style guide](https://github.com/bitemyapp/esqueleto/blob/master/style-guide.yaml).

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR.
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts).

2021-09-28 21:29 UTC, parsonsmatt requested changes
Looks fantastic!

I think a new instance is a minor version bump, not patch.

Could you add a changelog entry?

Thanks!

2021-09-28 21:29 UTC, parsonsmatt commented on esqueleto.cabal
> +version:        3.5.2.3
Adding instances is a minor bump

```suggestion
version:        3.5.3.0
```

2021-09-28 21:29 UTC, parsonsmatt commented on src/Database/Esqueleto/Experimental/From/Join.hs
> +-- @since 3.5.2.3
```suggestion
-- @since 3.5.3.0
```

2021-09-28 21:29 UTC, parsonsmatt commented on src/Database/Esqueleto/Experimental/From/Join.hs
> +-- @since 3.5.2.3
```suggestion
-- @since 3.5.3.0
```

2021-09-28 22:29 UTC, m4dc4p commented
Updates made.

2021-09-28 22:30 UTC, parsonsmatt approved these changes

2021-09-28 22:30 UTC, parsonsmatt commented
awesome, thank you!

2021-09-28 23:09 UTC, m4dc4p commented
Would you approve the workflow again so CI will run? Apparently this will have to happen each time I push :/

2021-09-30 16:26 UTC, parsonsmatt requested changes

2021-09-30 16:26 UTC, parsonsmatt commented on test/Common/Test.hs
> +      asserting (null $ drop 1000 result)
This pattern uses `noExceptions`

```suggestion
      asserting noExceptions
```

2021-09-30 16:26 UTC, parsonsmatt commented on test/Common/Test.hs
> +      let result :: [(PersonId, ProfileId, BlogPostId)] = [(a, b, c) | (Value a, Value b, Value c) <- rows]
can use `coerce` for this, too:

```suggestion
      let result = coerce rows :: [(PersonId, ProfileId, BlogPostId)]
```

2021-09-30 16:26 UTC, parsonsmatt commented on test/Common/Test.hs
> +    itDb "allows re-using (:&) joined tables" $ do
blessed tests 🙌🏻

2021-09-30 17:32 UTC, parsonsmatt approved these changes

2021-09-30 17:43 UTC, parsonsmatt commented
going to merge and fix locally, thanks for the contribution! 😄

2021-09-30 17:43 UTC, merged